import { Box, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { DashboardLayout } from "../layouts/DashboardLayout";
import work from "../assets/working.gif";

const Page = () => {
  return (
    <>
      <Head>
        <title>Frames</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/login.svg" 
         />
      </Head>


      <Stack
        sx={{
          display: "flex",

          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Image src={work} alt="work in progress" />
        <Typography variant="h2">Work in progress</Typography>
      </Stack>
    </>
  );
};
Page.getLayout = (page) => <DashboardLayout>{page}</DashboardLayout>;

export default Page;
