import {
  Box,
  Button,
  Container,
  Divider,
  Grid,
  ImageList,
  ImageListItem,
  Paper,
  Stack,
  Typography,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { DashboardLayout } from "../layouts/DashboardLayout";
import work from "../assets/working.gif";
import landingBackground from "../assets/landing-page-background.jpg";
import { AppLogo } from "@/components/custom-logo/app-logo";
import styled from "@emotion/styled";
import Link from "next/link";
import { useRouter } from "next/router";

const Page = () => {
  const Wrapper = styled("div")(({ theme }) => ({
    display: "flex",
    backgroundColor: "red",
    width: "100%",
    height: "10vh",
    flex: "1 1 auto",
    backgroundImage: "url(../assets/landing-page-background.jpg)",
    flexDirection: "column",
    // [theme.breakpoints.down("md")]: {
    //   backgroundColor: "red",
    // },
  }));

  const MyStyledButton = styled("button")(({ theme }) => ({
    backgroundColor: theme.primary,
  }));
  const router = useRouter();
  const { query } = router;
  return (
    <>
      <Head>
        <title>Frames</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/login.svg" />
      </Head>

      <Stack
        sx={{
          display: "flex",
          justifyContent: "center",
        }}
      >
        <Box
          sx={{
            display: "flex",
            backgroundColor: "grey",
            alignItems: "center",
            justifyContent: "center",
            width: "100%",
            textAlign: "center",
            height: "25em",
            padding: "0 1em",
            backgroundImage: `url(https://images.pexels.com/photos/2043739/pexels-photo-2043739.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)`,
          }}
        >
          <Typography
            sx={{
              fontSize: {
                lg: 35,
                md: 30,
                sm: 25,
                xs: 18,
              },
            }}
            color={"background.default"}
          >
            The best free stock photos, royalty free images shared by creators.
          </Typography>
        </Box>
        <Stack
          // maxWidth={"lg"}
          spacing={10}
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            margin: "1em auto",
          }}
          direction="row"
        >
          <Button
            color="secondary"
            sx={{ border: "1px solid" }}
            component={Link}
            variant={query?.type == null ? "contained" : "text"}
            href="/"
          >
            Wall
          </Button>
          <Button
            variant={query?.type == "following" ? "contained" : "text"}
            color="secondary"
            component={Link}
            href="?type=following"
          >
            Following
          </Button>
        </Stack>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Grid container maxWidth={"lg"} rowSpacing={1} columnSpacing={1}>
            {itemData.map((item) => (
              <Grid lg={3} md={4} sm={6} xs={12} item>
                <img
                  src={`${item.img}`}
                  srcSet={`${item.img}`}
                  alt={item.title}
                  loading="lazy"
                  width={"100%"}
                  height={"350px"}
                />
              </Grid>
            ))}
          </Grid>
        </Box>
      </Stack>
    </>
  );
};
const itemData = [
  {
    img: "https://images.unsplash.com/photo-1549388604-817d15aa0110",
    title: "Bed",
  },
  {
    img: "https://images.unsplash.com/photo-1525097487452-6278ff080c31",
    title: "Books",
  },
  {
    img: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6",
    title: "Sink",
  },
  {
    img: "https://images.unsplash.com/photo-1563298723-dcfebaa392e3",
    title: "Kitchen",
  },
  {
    img: "https://images.unsplash.com/photo-1588436706487-9d55d73a39e3",
    title: "Blinds",
  },
  {
    img: "https://images.unsplash.com/photo-1574180045827-681f8a1a9622",
    title: "Chairs",
  },
  {
    img: "https://images.unsplash.com/photo-1530731141654-5993c3016c77",
    title: "Laptop",
  },
  {
    img: "https://images.unsplash.com/photo-1481277542470-605612bd2d61",
    title: "Doors",
  },
  {
    img: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7",
    title: "Coffee",
  },
  {
    img: "https://images.unsplash.com/photo-1516455207990-7a41ce80f7ee",
    title: "Storage",
  },
  {
    img: "https://images.unsplash.com/photo-1597262975002-c5c3b14bbd62",
    title: "Candle",
  },
  {
    img: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
    title: "Coffee table",
  },
  {
    img: "https://images.unsplash.com/photo-1549388604-817d15aa0110",
    title: "Bed",
  },
  {
    img: "https://images.unsplash.com/photo-1525097487452-6278ff080c31",
    title: "Books",
  },
  {
    img: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6",
    title: "Sink",
  },
  {
    img: "https://images.unsplash.com/photo-1563298723-dcfebaa392e3",
    title: "Kitchen",
  },
  {
    img: "https://images.unsplash.com/photo-1588436706487-9d55d73a39e3",
    title: "Blinds",
  },
  {
    img: "https://images.unsplash.com/photo-1574180045827-681f8a1a9622",
    title: "Chairs",
  },
  {
    img: "https://images.unsplash.com/photo-1530731141654-5993c3016c77",
    title: "Laptop",
  },
  {
    img: "https://images.unsplash.com/photo-1481277542470-605612bd2d61",
    title: "Doors",
  },
  {
    img: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7",
    title: "Coffee",
  },
  {
    img: "https://images.unsplash.com/photo-1516455207990-7a41ce80f7ee",
    title: "Storage",
  },
  {
    img: "https://images.unsplash.com/photo-1597262975002-c5c3b14bbd62",
    title: "Candle",
  },
  {
    img: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
    title: "Coffee table",
  },
];
Page.getLayout = (page) => <DashboardLayout>{page}</DashboardLayout>;

export default Page;
